function U = Policy_Exp_Welfare(x, tauc_exp, epsilon_exp)
    % Objective function for policy optimization (fmincon)
    % Calculates the negative of social welfare to be minimized

    % Load baseline parameters and grid setup
    load('base')

    % --- Set Elasticity of Substitution (EoS) and Marginal Damages ---
    % Based on the experiment case (epsilon_exp), toggle between baseline and alternative EoS
    if epsilon_exp == 1
        epsilon_cal = epsilon_alt;  % High elasticity
        mep = mep2;                 % Associated damage parameter
    elseif epsilon_exp == 0
        epsilon_cal = epsilon_base; % Low elasticity
        mep = mep1;                 % Associated damage parameter
    end                                                         

    % --- Construct Policy Shock Path ---
    % Initialize shock vectors
    tauc_shock = ones(T+2, 1);
    taud_shock = ones(T+2, 1);
       
    % Build a piecewise constant/blocked shock path from decision variables (x)
    shock = zeros(T+2, 1);
    shock(1) = 1;               % No shock in the initial period
    shock(2:40) = x(1:39);      % First 39 periods are determined by individual x elements
    
    % Group subsequent periods into blocks of 40 to reduce optimization dimensionality
    block_starts = 41:40:360;
    for i = 1:length(block_starts)
        shock(block_starts(i):block_starts(i)+39) = x(39+i);
    end
    shock(361:T+2) = x(48);     % Terminal period value
    
    % Assign constructed shock path to either Clean Subsidy (tauc) or Dirty Tax (taud)
    if tauc_exp == 1
        tauc_shock = shock;
    elseif tauc_exp == 0
        taud_shock = shock;
    end 
        
    % Set terminal steady-state values for Dynare's endval block
    tauc_end = tauc_shock(T+2);
    taud_end = taud_shock(T+2);

    % --- Dynare Execution ---
    % Save inputs to a .mat file for the .mod file to load
    save('dynare_in');

    % Execute Dynare simulation (Deterministic/Perfect Foresight)
    dynare ModelFinal

    % Load results generated by Dynare
    load ModelFinal_results.mat oo_ M_ options_

    % --- Data Extraction ---
    % Locate consumption (c) and dirty energy (zd) in the endogenous variable list
    idx_c = strmatch('c', M_.endo_names, 'exact');
    c_in = oo_.endo_simul(idx_c, :);

    idx_zd = strmatch('zd', M_.endo_names, 'exact');
    zd_in = oo_.endo_simul(idx_zd, :);

    % Transform intensive form variables (per capita) back to levels
    C_out = c_in'.*Level;
    Zd_out = zd_in'.*Level;

    % --- Welfare Calculation ---
    % Compute Social Welfare using the welfarePOP function
    % Return as negative value (U) because fmincon is a minimizer
    U = - welfarePOP(C_out, Zd_out, mep, beta_cal, g_cal, eta0, eta_g_cal, gl_cal, L);

end